# fly.toml app configuration file generated for telegram-ai-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telebot"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

[processes]
  app = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
